Create --help option
TypedDevs/bashunit pull request #161
Opened 2023-10-10 20:26 UTC by Chemaclass

## 🔖 Changes

- Add `--help` option

## 🖼️ Screenshots

<img width="766" alt="Screenshot 2023-10-10 at 22 24 33" src="https://github.com/TypedDevs/bashunit/assets/5256287/ac56e8eb-0093-47f2-9e12-65888a351d8b">

2023-10-10 21:30 UTC, JesusValera approved these changes

2023-10-11 04:58 UTC, Tito-Kati requested changes
I would also add a link to the web documentation and don't forget to add this argument to the documentation.

2023-10-11 08:19 UTC, Tito-Kati commented on docs/command-line.md
> +    [...]
```suggestion
  -f|--filer
    Filters the tests to run based on the test name.

  [...]
```

2023-10-11 08:19 UTC, Tito-Kati approved these changes

2023-10-11 08:27 UTC, merged