chore: assert_contains_ignore_case
TypedDevs/bashunit pull request #196
Opened 2023-10-16 14:16 UTC by raphaelstolt

## 📚 Description

Adds the `assert_contains_ignore_case` assertion.

## ✅ To-do list

- [x] I updated the `CHANGELOG.md` to reflect the new feature
- [x] I updated the documentation to reflect the changes

2023-10-16 14:26 UTC, Chemaclass commented
Thanks for contributing, @raphaelstolt! Can you double-check the [failing tests](https://github.com/TypedDevs/bashunit/actions/runs/6534911497/job/17743402183?pr=196)?

<img width="561" alt="Screenshot 2023-10-16 at 16 25 52" src="https://github.com/TypedDevs/bashunit/assets/5256287/97b8615b-6eff-4045-bbbc-ead81ddf5dc3">

2023-10-16 14:57 UTC, Chemaclass approved these changes
Thanks a lot! 👏

2023-10-16 16:10 UTC, Tito-Kati requested changes
Thank you so much for your contribution @raphaelstolt ! If you don't mind adding my suggestion (a good example in the documentation for a better DX) it would be the icing on the cake.

2023-10-16 16:10 UTC, Tito-Kati commented on docs/assertions.md
>  :::
````suggestion
## assert_contains_ignore_case
> `assert_contains_ignore_case "needle" "haystack"`

Reports an error if `needle` is not a substring of `haystack`.
Differences in casing are ignored when needle is searched for in haystack.

::: code-group
```bash [Example]
function test_success() {
  assert_contains_ignore_case "foo" "FooBar"
}

function test_failure() {
  assert_contains_ignore_case "baz" "FooBar"
}
```
:::
````

2023-10-16 18:34 UTC, Tito-Kati commented
closes #178

2023-10-16 20:57 UTC, JesusValera approved these changes

2023-10-17 05:23 UTC, raphaelstolt commented
Documentation is updated as suggested.

2023-10-17 06:10 UTC, khru approved these changes
Looks good

2023-10-17 06:11 UTC, khru commented on docs/assertions.md
>  :::
Done @Tito-Kati

2023-10-17 06:15 UTC, Tito-Kati approved these changes

2023-10-17 06:16 UTC, merged

2023-10-17 06:17 UTC, khru commented
Kudo @raphaelstolt you've done a nice job, thank you for helping and supporting the project :heart: