Allow install main
TypedDevs/bashunit pull request #211
Opened 2023-10-30 13:45 UTC by Chemaclass

## 📚 Description

Issue: https://github.com/TypedDevs/bashunit/issues/210

Currently, the [installer tool](https://bashunit.typeddevs.com/installation#install-sh) allows you to install a concrete version, once it was release. However, there is no easy way to benefit of the features/bug-fixes already merged into main unless you download the project and run the build.sh yourself.

## 🔖 Changes

- Allow using main as [version], to get the main branch and build the "main non-stable" bashunit version.

## ✅ To-do list

- [x] I updated the `CHANGELOG.md` to reflect the new feature or fix
- [x] I updated the documentation to reflect the changes

![Screenshot 2023-10-30 at 14 44 47](https://github.com/TypedDevs/bashunit/assets/5256287/b929d2f2-f38e-4c0a-b1a6-3bd0549567f7)

2023-11-04 16:14 UTC, Chemaclass commented
Can you help me with the failing test, @Tito-Kati or @khru ? I cannot reproduce it locally (with my MacOS) 🤔

2023-11-07 17:41 UTC, Tito-Kati commented on build.sh
> +chmod u+x bin/bashunit
👍🏻

2023-11-07 17:51 UTC, Tito-Kati requested changes

2023-11-07 17:51 UTC, Tito-Kati commented on install.sh
> +  echo "> bashunit has been installed in the '$DIR' folder"
This echo is the same in both functions; could it be moved to the end of the script to avoid duplication?

2023-11-07 17:51 UTC, Tito-Kati commented on install.sh
> +  install_concrete_version
Rename:
- install_concrete_version to install
- install_main to install_non_stable

2023-11-07 17:51 UTC, Tito-Kati commented on install.sh
> +if [[ $VERSION == 'main' ]]; then
Devs don't need to know the name of the branch, change main to next, preview, non-stable... 🤷🏻

2023-11-07 17:51 UTC, Tito-Kati commented on tests/acceptance/install_test.sh
> +}
Extra acceptance test with the combination of main and specifying the installation directory.

2023-11-07 17:51 UTC, Tito-Kati commented on install.sh
> +if [[ $VERSION == 'main' ]]; then
Make sure to change main to the new word you choose everywhere (tests, docs, messages, etc...).

2023-11-08 10:37 UTC, Tito-Kati approved these changes

2023-11-08 10:41 UTC, Tito-Kati commented
I've fixed the error that the workflows were giving on Linux. By removing the git mock, I could have fixed the mock, but being an acceptance test, it seemed more correct to remove it.

Additionally, I've taken the liberty of applying the corrections I requested myself and making a few more minor changes.

2023-11-08 10:50 UTC, khru commented on install.sh
> +  curl -L -O -J "https://github.com/TypedDevs/bashunit/releases/download/$TAG/bashunit" 2>/dev/null
Would it make senses to add header on the `curl` to track the version requested as well as the OS that is using?

2023-11-08 10:51 UTC, khru commented on install.sh
> +  curl -L -O -J "https://github.com/TypedDevs/bashunit/releases/download/$TAG/bashunit" 2>/dev/null
https://reqbin.com/req/c-ea0d5rlb/curl-send-header-example

2023-11-08 10:53 UTC, khru requested changes

2023-11-08 10:53 UTC, khru commented on tests/acceptance/install_test.sh
> +  assert_equals "$(printf "\e[1m\e[32mbashunit\e[0m - (non-stable) beta")" "$("$install_dir" --version)"
We are missing to test that the dir has been deleted

2023-11-09 16:25 UTC, khru approved these changes

2023-11-09 16:25 UTC, merged